package pt.isec.a21280348.bigmath.multiplayer

enum class ConnectionState {
    AWAITING_PLAYERS,
    CONNECTION_ESTABLISHED,
    SETTING_PARAMETERS,
    CONNECTION_ERROR,
    CLIENT_CONNECTING
}

enum class GameState {
    WAITING_FOR_PLAYERS,
    WAITING_FOR_ANSWER,
    WAITING_FOR_NEXT_QUESTION,
    GAME_OVER
}